<?php

return [
    0 => [
        'name' => 'maptype',
        'title' => '默认地图类型',
        'type' => 'radio',
        'content' => [
            'baidu' => '百度地图',
            'amap' => '高德地图',
            'tencent' => '腾讯地图',
        ],
        'value' => 'baidu',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    1 => [
        'name' => 'location',
        'title' => '默认检索城市',
        'type' => 'string',
        'content' => [
        ],
        'value' => '北京',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    2 => [
        'name' => 'zoom',
        'title' => '默认缩放级别',
        'type' => 'string',
        'content' => [
        ],
        'value' => '12',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    3 => [
        'name' => 'lat',
        'title' => '默认Lat',
        'type' => 'string',
        'content' => [
        ],
        'value' => '39.919990',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    4 => [
        'name' => 'lng',
        'title' => '默认Lng',
        'type' => 'string',
        'content' => [
        ],
        'value' => '116.456270',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    5 => [
        'name' => 'baidukey',
        'title' => '百度地图KEY',
        'type' => 'string',
        'content' => [
        ],
        'value' => 'hAeMFHmpyHa2ZjaCH9VVridl',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    6 => [
        'name' => 'amapkey',
        'title' => '高德地图KEY',
        'type' => 'string',
        'content' => [
        ],
        'value' => '608d75903d29ad471362f8c58c550daf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    7 => [
        'name' => 'tencentkey',
        'title' => '腾讯地图KEY',
        'type' => 'string',
        'content' => [
        ],
        'value' => '608d75903d29ad471362f8c58c550daf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    8 => [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => '',
        'content' => [
        ],
        'value' => '请先申请对应地图的Key，配置后再使用',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => 'alert-danger-light',
    ],
];
